services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    environment:
      - NODE_ENV=development

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    ports:
      - "5001:5001"
    volumes:
      - ./server:/app
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=development
      - PORT=5001
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
