version: '3.9'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client  # Path to the client Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    environment:
      - NODE_ENV=development

  server:
    build:
      context: .
      dockerfile: Dockerfile.server  # Path to the server Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
