# Use the official Node.js image as the base image
FROM node:18

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY server/package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY server/ .

# Expose the port on which the server will run
EXPOSE 5000

# Command to run the server in development mode
CMD ["npm", "run", "dev"]
